x-base: &base
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/app
  env_file:
    - env

services:
  app:
    <<: *base
    container_name: app
    ports:
      - "80:8000"
    command: daphne -b 0.0.0.0 -p 8000 app.asgi:application
    depends_on:
      - init-app
    restart: on-failure

  init-app:
    <<: *base
    container_name: init-app
    command: python manage.py migrate
    depends_on:
      - db
    restart: on-failure

  db:
    container_name: db
    image: postgres:latest
    env_file:
      - env
    ports:
      - "5432:5432"