# Generated by Django 5.1.6 on 2025-02-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asynctest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='saved',
            field=models.IntegerField(default=0),
        ),
    ]
