# Generated by Django 5.1.6 on 2025-02-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asynctest', '0002_test_saved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='MyModel',
        ),
    ]
